### ISSUE TITLE
Vote for Tay

### ISSUE THREAD

**Issue by dannyfritz** [sreynen/vote#5]
He is the only non-education-reformer of the 3. Bolster neighborhood schools to bring back community and equity. We need less Choice advocates in gov. Choice is causing needless traffic/pollution, leading to school closures, and creating winners and losers.

https://www.youtube.com/watch?v=ThUI9b4pPOs

**Comment by sreynen** [comment]
https://github.com/sreynen/vote/commit/e14c54ea27f884c6a0351712b05492d521ce7cda
